use_frameworks!

platform :ios, '9.0'

target 'PodCreateSample_Example' do
  pod 'PodCreateSample', :path => '../'

  target 'PodCreateSample_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
